server:
  appName: keeper-events
  name: events
  port: 0
  ip: host.docker.internal
  endpoint:
    main: api/events
  eureka:
    enabled: true
    hostname: host.docker.internal
    prefer-ip: true
  db:
    host: keeper-postgres
    port: 5432
    name: keeper-postgres-db
    schema: events
    user: ditar
    password: keeperAdmin1984
  logging:
    level: info
    filePath: ../logs/events/events.log

