server:
  appName: keeper-events
  name: events
  port: 0
  ip: 0.0.0.0
  endpoint:
    main: api/events
  eureka:
    enabled: true
  db:
    port: 11984
    name: keeper-postgres-db
    schema: events
    user: ditar
    password: keeperAdmin1984
  logging:
    level: info
    filePath: ../logs/events/events.log

