server:
  appName: keeper-events-service
  name: events
  port: 8092
  ip: localhost
  endpoint:
    main: api/events
  db:
    port: 5432
    name: postgres
    schema: events
    user: postgres
    password: postgrespw
  logging:
    level: info
    filePath: ../logs/events/panda.log

