server:
  appName: keeper-events-service
  name: keeper_events
  port: 0
  ip: host.docker.internal
  eureka:
    enabled: true
    hostname: host.docker.internal
    prefer-ip: true
  endpoint:
    main: api/v1/events
  db:
    port: 5432
    name: postgres
    schema: keeper_events
    user: postgres
    password: postgrespw
  logging:
    level: info
    filePath: ../logs/events/panda.log

